name: Run UI Tests

on:
  pull_request:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install root dependencies
        run: yarn install --frozen-lockfile

      - name: Install backend dependencies
        working-directory: ./backend
        run: yarn install --frozen-lockfile

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Install UI test dependencies
        working-directory: ./frontend/__ui__
        run: yarn install --frozen-lockfile

      - name: Start backend
        working-directory: ./backend
        run: yarn start &
        
      - name: Start frontend
        working-directory: ./frontend
        run: yarn dev &

      - name: Wait for servers to be ready
        run: sleep 15

      - name: Install Playwright browsers
        working-directory: ./frontend/__ui__
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./frontend/__ui__
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/__ui__/playwright-report/
          retention-days: 30